name: hydraline_example
description: Full-stack Hydraline showcase - Flutter Web app + SSR server + SSG.
publish_to: none
version: 0.0.3

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  hydraline: ^0.0.3
  hydraline_flutter: ^0.0.3
  hydraline_server: ^0.0.3
  shelf: ^1.4.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
