/// Dispatcher JS (≤2 KB).
///
/// Global `window.hydraline` API, all hydration directives
/// (onLoad/onIdle/onVisible/onInteraction/onMedia/manual), `data-hydration`
/// lifecycle, timeout and retry.
library;

const jsDispatcher =
    r'''(()=>{var d=document,w=window,H,o=null,l=!1,e=!1,g=!1,r=null,Y='data-hydration',N='hydraline-island',D='data-directive';function Q(i){return d.querySelector(N+'[id="'+i+'"]')||d.querySelector('[data-island="htmx"][id="'+i+'"]')}function F(e,r){e.setAttribute(Y,'failed');e.dispatchEvent(new CustomEvent('hydraline:island-error',{bubbles:!0,detail:{id:e.id,reason:r}}))}function K(i,f){var e=Q(i);if(!e)return;e.setAttribute(Y,'hydrating');var t=setTimeout(()=>{F(e,'timeout')},15000);f().then(()=>{clearTimeout(t);e.setAttribute(Y,'hydrated')},(r)=>{clearTimeout(t);F(e,r+'')})}function X(i,f){if(e)return K(i,f);if(g)return(r=r||[]).push([i,f]);g=!0;var s=d.createElement('script');s.src='/main.dart.js';s.onload=()=>{e=!0;K(i,f);(r||[]).forEach((p)=>{K(p[0],p[1])});r=null};d.head.appendChild(s)}H=function(i){var e=Q(i);if(!e||e.getAttribute(Y)==='hydrated')return;var f=e.getAttribute('data-island-level')==='htmx'?null:X;if(f)f(i,()=>Promise.resolve())};w.hydraline={hydrate:H,hydrateAll:function(){for(var s=d.querySelectorAll(N+'['+D+'="hydrateManual"],[data-island="htmx"]['+D+'="hydrateManual"]'),i=0;i<s.length;i++)H(s[i].id)}};d.addEventListener('DOMContentLoaded',()=>{var s,i,v,a;for(s=d.querySelectorAll(N),i=0;i<s.length;i++)if(s[i].getAttribute(D)==='hydrateOnLoad')H(s[i].id);v=d.querySelectorAll(N+'['+D+'="hydrateOnVisible"]');if(v.length&&!o){o=new IntersectionObserver((e,ob)=>{e.forEach((x)=>{if(x.isIntersecting){H(x.target.id);ob.unobserve(x.target)}})},{rootMargin:'200px'});for(i=0;i<v.length;i++)o.observe(v[i])}a=d.querySelectorAll(N+'['+D+'="hydrateOnIdle"]');if(a.length&&!l){l=()=>{for(i=0;i<a.length;i++)H(a[i].id)};(w.requestIdleCallback||setTimeout)(l)}if(!w._hd){w._hd=!0;d.addEventListener('click',(ev)=>{var e=ev.target;while(e&&e!==d){if(e.matches&&e.matches(N+'['+D+'="hydrateOnInteraction"]')){H(e.id);return}e=e.parentNode}},!0)}s=d.querySelectorAll(N+'['+D+'="hydrateOnMedia"]');for(i=0;i<s.length;i++){(function(e){var q=e.getAttribute('data-media');if(q&&w.matchMedia(q).matches)H(e.id)})(s[i])}})})()''';
